### ISSUE TITLE
Not work with last papertrail RC

### ISSUE THREAD

**Issue by fmh** [rikkipitt/rails_admin_history_rollback#4]
It seem that the index method for version object has disappeared from this papertrail RC

```
ActionView::Template::Error (undefined method `index' for #<PaperTrail::Version:0x007fe960919fa0>):
    1: %table#version.table.table-striped{:data => { :title => "#{@abstract_model} version ##{@version.index + 1} <small>[#{@version.event}]</small>", :rollbackurl => url_for(action: action(:history_index, @abstract_model).action_name, model_name: @abstract_model.to_param, version_id: @version.id), rollback: t("admin.history_rollback.table_headers.rollback"), cancel: t("admin.history_rollback.cancel"), confirm: t("admin.history_rollback.confirm")}}
    2:   %thead
    3:     %tr
    4:       %th= "#{t('admin.history_rollback.table_headers.field')}"
  activemodel (4.2.3) lib/active_model/attribute_methods.rb:433:in `method_missing'
  rails_admin_history_rollback (0.0.5) app/views/rails_admin/main/_version.html.haml:1:in `___sers_fmh__rvm_gems_ruby_______gems_rails_admin_history_rollback_______app_views_rails_admin_main__version_html_haml__3289281808284976726_70320173280960'
  actionview (4.2.3) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.3) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.3) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.3) lib/action_view/template.rb:143:in `render'
  actionview (4.2.3) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
```

**Comment by fmh** [comment]
It's not related to your gem, but because Papertrail 4.0.0 no longer support/recommend initializer (config/initializers/paper_trail.rb)  like in my use case.
https://github.com/airblade/paper_trail/blob/master/CHANGELOG.md

**Comment by rikkipitt** [comment]
@fmh thanks for reporting and letting me know!
